# Generated by Django 4.2.2 on 2024-02-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image_link',
            field=models.CharField(default='https://f.hubspotusercontent20.net/hubfs/182473/HealthBenefitsFitness.png', max_length=255),
        ),
    ]
