# Generated by Django 4.2.2 on 2024-03-03 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_exercise_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutexercise',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='workout',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
        migrations.DeleteModel(
            name='WorkoutExercise',
        ),
    ]
